version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade pip
      - if [ -f "functional_tests/requirements.txt" ]; then pip install -r functional_tests/requirements.txt; fi
      - cd src/lambda && if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi && cd ../..
      - cd src/glue && if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi && cd ../..
      
  pre_build:
    commands:
      - echo "Running functional tests"
      - echo "Current directory structure:"
      - ls -la
      - echo "Functional tests directory structure:"
      - ls -la functional_tests
      - echo "Test data directory structure:"
      - ls -la functional_tests/test_Data
      - cd functional_tests
      - behave features/data_accuracy.feature -f pretty
      - cd ..
      
  build:
    commands:
      - echo "Packaging Lambda function"
      - cd src/lambda
      - zip -r ../../function.zip ./*
      - cd ../..
      
      - echo "Packaging Glue job"
      - cd src/glue
      - zip -r ../../glue_job.zip ./*
      - cd ../..
      
  post_build:
    commands:
      - echo "Deploying artifacts"

artifacts:
  files:
    - function.zip
    - glue_job.zip
    - src/**/*
    - buildspec.yml
  base-directory: '.'

cache:
  paths:
    - '/root/.cache/pip/**/*'